### PR TITLE
Update tcf-agent download URL

### PR DESCRIPTION
**Pull request by kalvdans**
Seems eclipse have changed their git URL.

### CODE REVIEW

**Comment by kalvdans** [comment]
As discussed here: https://stackoverflow.com/questions/59600440/about-the-wrong-uri-in-tcf-agent-git-bb-in-poky#answer-70287698

**Comment by mhatle** [comment]
We're trying to avoid diverging from upstream Poky.   I would suggest seeing if they already have this change.  If so I can back port it in from there.  If they don't have this change, then it needs to be made in another layer, most likely meta-petalinux.

**Comment by mhatle** [comment]
rejecting, for now.   See previous.

**Comment by kalvdans** [comment]
Thanks @mhatle for a prompt decision! As I'm new to yocto, please bear with me. I found the upstream commit at https://git.yoctoproject.org/poky/commit/?id=79b7ce12c1bb474a9af5411886e11897032a230d but it has not been backported to their `gatesgarth` branch yet, which I assume is the upstream branch that `rel-v2021.1` is tracking. Do you suggest me to ask the commit to be backported, on their mailing list poky@lists.yoctoproject.org ?

**Comment by kalvdans** [comment]
To answer myself, the upstream branch `gatesgarth` is [end-of-life](https://wiki.yoctoproject.org/wiki/Releases) and not accepting any patches.

**Pull request closed without merging**
